[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {path = "../common"}
backend = {path = "../backend"}

log = "0.4"
env_logger = "0.11"

tokio = { version = "1", features = ["full"] }